#!/usr/bin/python
import time
from subprocess import call
from os import listdir
import random

interval = 5 #in minutes
path = '/home/andlun/Pictures/UseWallpapers/'
while True:
	files = listdir(path)
	f = random.choice(files)
	call(['fbsetbg', path + f])
	time.sleep(60*interval)
